/*
  # Fix Recommendations Table

  1. Changes
    - Drop and recreate recommendations table with TEXT id (not UUID)
    - This matches the frontend code which uses Date.now().toString() for ids
  
  2. Table Structure
    - id: TEXT (primary key, manually generated by app)
    - type: TEXT (movie/music/book)
    - title: TEXT
    - creator: TEXT (optional)
    - release_date: TEXT (optional)
    - synopsis: TEXT (optional)
    - comment: TEXT (Wade's comment)
    - cover_url: TEXT (optional)
    - luna_review: TEXT (optional)
    - luna_rating: INTEGER (1-5, optional)
    - wade_reply: TEXT (optional)
    - created_at: TIMESTAMP WITH TIME ZONE
  
  3. Security
    - Enable RLS
    - Allow all operations for testing (no auth required)
*/

CREATE TABLE IF NOT EXISTS recommendations (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('movie', 'music', 'book')),
  title TEXT NOT NULL,
  creator TEXT,
  release_date TEXT,
  synopsis TEXT,
  comment TEXT NOT NULL DEFAULT '',
  cover_url TEXT,
  luna_review TEXT,
  luna_rating INTEGER CHECK (luna_rating >= 1 AND luna_rating <= 5),
  wade_reply TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations on recommendations"
ON recommendations
FOR ALL
USING (true)
WITH CHECK (true);